# Generated by Django 4.2.4 on 2024-01-25 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad_point', '0002_squadpoint_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadpoint',
            name='point',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
