# Generated by Django 4.2.4 on 2024-07-09 16:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge_person', '0003_judgeperson_gender_judgeperson_height_cm_and_more'),
        ('condition_point', '0001_initial'),
        ('squad', '0003_alter_squad_id'),
        ('squad_point', '0003_alter_squadpoint_point'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='squadpoint',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='squadpoint',
            name='condition_point_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condition_point.conditionpoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='squadpoint',
            name='point',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterUniqueTogether(
            name='squadpoint',
            unique_together={('squad_id', 'judge_person_id', 'condition_point_id')},
        ),
    ]
