# Generated by Django 4.2.4 on 2023-10-05 09:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomination', '0003_alter_conditionperformance_nomination_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('performance_date_time', models.DateTimeField()),
                ('nomination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomination.nomination')),
            ],
            options={
                'unique_together': {('squad_name', 'nomination_id')},
            },
        ),
    ]
