# Generated by Django 4.2.4 on 2023-10-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='performance_date_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
