# Generated by Django 4.2.4 on 2023-10-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0002_alter_squad_performance_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
