# Generated by Django 4.2.4 on 2023-10-03 08:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports_person', '0006_personrank_remove_sportsperson_rank_and_more'),
        ('competition', '0004_alter_competition_competition_qty_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomination_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('nomination_start_date_time', models.DateTimeField()),
                ('performance_second', models.IntegerField()),
                ('delay_between_performance_second', models.IntegerField()),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionPerformance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('men_person', models.BooleanField(default=True)),
                ('women_person', models.BooleanField(default=True)),
                ('min_qty_person', models.IntegerField(default=1)),
                ('max_qty_person', models.IntegerField(default=99)),
                ('min_age_person', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)])),
                ('max_age_person', models.IntegerField(default=250, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)])),
                ('min_weight_person', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)])),
                ('max_weight_person', models.IntegerField(default=250, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)])),
                ('min_height_person', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)])),
                ('max_height_person', models.IntegerField(default=250, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)])),
                ('max_rank_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='max_rank_condition', to='sports_person.personrank', to_field='person_rank_name')),
                ('min_rank_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_rank_condition', to='sports_person.personrank', to_field='person_rank_name')),
                ('nomination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomination.nomination')),
            ],
        ),
    ]
