# Generated by Django 4.2.4 on 2023-10-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_alter_competition_competition_qty_days'),
        ('nomination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionperformance',
            name='nomination_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
    ]
