# Generated by Django 4.2.4 on 2023-10-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0002_alter_conditionperformance_nomination_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionperformance',
            name='nomination_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomination.nomination'),
        ),
    ]
