# Generated by Django 4.2.4 on 2023-10-10 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0003_alter_conditionperformance_nomination_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionperformance',
            name='max_age_person',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='conditionperformance',
            name='max_height_person',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='conditionperformance',
            name='max_qty_person',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='conditionperformance',
            name='max_weight_person',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='conditionperformance',
            name='min_age_person',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='conditionperformance',
            name='min_height_person',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='conditionperformance',
            name='min_qty_person',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='conditionperformance',
            name='min_weight_person',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
