# Generated by Django 4.2.4 on 2023-09-19 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)])),
                ('competition_city', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('competition_date', models.DateField()),
                ('competition_qty_days', models.IntegerField(max_length=2)),
            ],
        ),
    ]
