# Generated by Django 4.2.4 on 2023-09-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_competition_competition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition_qty_days',
            field=models.IntegerField(),
        ),
    ]
