# Generated by Django 4.2.4 on 2023-10-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_alter_competition_competition_qty_days'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competition',
            unique_together={('competition_name', 'competition_city', 'competition_date')},
        ),
    ]
