# Generated by Django 4.2.4 on 2023-09-18 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JudgePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('birth_day', models.DateField()),
                ('team', models.CharField(default=None, max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('rank', models.CharField(default=None, max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('license_expiration_date', models.DateField()),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'birth_day')},
            },
        ),
    ]
