# Generated by Django 4.2.4 on 2023-09-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge_person', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='judgeperson',
            unique_together={('first_name', 'last_name', 'rank')},
        ),
    ]
