# Generated by Django 4.2.4 on 2023-09-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_person', '0002_alter_city_city_alter_ranksportsperson_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsperson',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='sportsperson',
            name='rank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sportsperson',
            name='team',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='RankSportsPerson',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
