# Generated by Django 4.2.4 on 2023-09-18 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_person', '0003_alter_sportsperson_city_alter_sportsperson_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsperson',
            name='city',
            field=models.CharField(default=None, max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='sportsperson',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='sportsperson',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='sportsperson',
            name='rank',
            field=models.CharField(default=None, max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='sportsperson',
            name='team',
            field=models.CharField(default=None, max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterUniqueTogether(
            name='sportsperson',
            unique_together={('first_name', 'last_name', 'birth_day')},
        ),
    ]
