# Generated by Django 4.2.4 on 2024-08-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_person', '0006_personrank_remove_sportsperson_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsperson',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=15, null=True),
        ),
    ]
