# Generated by Django 4.2.4 on 2023-10-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports_person', '0006_personrank_remove_sportsperson_rank_and_more'),
        ('squad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_person.sportsperson')),
                ('squad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squad.squad')),
            ],
            options={
                'unique_together': {('squad_id', 'sports_person_id')},
            },
        ),
    ]
