# Generated by Django 4.2.4 on 2024-08-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_community_background_url'),
        ('core', '0002_user_is_coach_user_is_judge_user_is_observer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='community_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='community.community'),
            preserve_default=False,
        ),
    ]
