# Generated by Django 4.2.4 on 2024-08-06 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_community_background_url'),
        ('core', '0004_alter_user_community_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='community_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='community.community'),
        ),
    ]
