# Generated by Django 4.2.4 on 2024-07-09 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('min_range_point', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)])),
                ('max_range_point', models.IntegerField(default=250, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)])),
                ('group_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.CharField(default=None, max_length=1000, null=True)),
            ],
        ),
    ]
