# Generated by Django 4.2.4 on 2024-08-03 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionpoint',
            name='condition_name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
