# Generated by Django 4.2.4 on 2024-08-03 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.CharField(max_length=250, null=True)),
                ('expiration_date', models.DateField()),
                ('status', models.BooleanField()),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='community_c_status_078e14_idx')],
            },
        ),
    ]
