# Generated by Django 4.2.4 on 2024-08-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='background_url',
            field=models.URLField(default=None, max_length=255, null=True),
        ),
    ]
