# Generated by Django 4.2.4 on 2024-08-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_background_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='background_url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
